version: '3.8'
services:
  db:
    image: postgres:15
    container_name: stms_01_db
    restart: always
    environment:
      POSTGRES_USER: miko_user
      POSTGRES_PASSWORD: miko123
      POSTGRES_DB: stms_db
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./layer2_backend
    container_name: stms_01_backend
    restart: always
    environment:
      TZ: Asia/Jakarta
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./layer2_backend:/app/stms # Mount folder video dari layer1_cv

volumes:
  postgres_data:
